name: key vault with dns failback
on: workflow_dispatch
jobs:  
  job1:
    permissions:
      contents: none
    runs-on: ubuntu-latest       
    steps:
    - name: checkout
      uses: actions/checkout@v2 
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_Deloitte}}
        enable-AzPSSession: true   
    - name: Update recordset of Private DNS Zone
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./key_vault_dns_failback.ps1 -primary_subscription_Id "${{vars.PRIVATE_DNS_ZONE_SUBSCRIPTION_ID}}" -private_DNS_Zone_resource_group_name "${{vars.PRIVATE_DNS_ZONE_RESOURCE_GROUP_NAME}}" -zone_name "${{vars.PRIVATE_DNS_ZONE_NAME}}" -record_name "${{vars.KEY_VAULT_1_PRIVATE_DNS_ZONE_RECORD_NAME}}" -newIP "${{vars.KEY_VAULT_1_PRIMARY_PRIVATE_ENDPOINT_IP}}" -oldIP "${{vars.KEY_VAULT_1_SECONDARY_PRIVATE_ENDPOINT_IP}}"
        azPSVersion: "latest"
