name: key vault with dns failback
on:
  workflow_call:
    inputs:
      primary_subscription_Id:
        required: true
        type: string
      private_dns_zone_resource_group_name:
        required: true
        type: string
      key_vault_private_dns_zone_record_name:
        required: true
        type: string
      key_vault_private_dns_zone_name:
        required: true
        type: string
      key_vault_primary_private_endpoint_IP:
        required: true
        type: string
      key_vault_secondary_private_endpoint_IP:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS_DELOITTE_SUB:
        required: true  
jobs:  
  job1:
    permissions:
      contents: none
    runs-on: ubuntu-latest       
    steps:
    - name: checkout
      uses: actions/checkout@v2 
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_Deloitte}}
        enable-AzPSSession: true   
    - name: Update recordset of Private DNS Zone
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./key_vault_dns_failback.ps1 -primary_subscription_Id "${{vars.PRIVATE_DNS_ZONE_SUBSCRIPTION_ID}}" -private_dns_zone_resource_group_name "${{vars.PRIVATE_DNS_ZONE_RESOURCE_GROUP_NAME}}" -key_vault_private_dns_zone_name "${{vars.KEY_VAULT_PRIVATE_DNS_ZONE_NAME}}" -key_vault_private_dns_zone_record_name "${{vars.KEY_VAULT_1_PRIVATE_DNS_ZONE_RECORD_NAME}}" -key_vault_primary_private_endpoint_IP "${{vars.KEY_VAULT_1_PRIMARY_PRIVATE_ENDPOINT_IP}}" -key_vault_secondary_private_endpoint_IP "${{vars.KEY_VAULT_1_SECONDARY_PRIVATE_ENDPOINT_IP}}"
        azPSVersion: "latest"
